In [65]:
#Importing files
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [66]:
df= sns.load_dataset('iris')

In [67]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [68]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [69]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [70]:
from sklearn.model_selection import train_test_split

In [71]:
X=df.drop('species', axis = 1)
y=df['species']

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [73]:
from sklearn.neighbors import KNeighborsClassifier

In [74]:
model_KNN = KNeighborsClassifier(n_neighbors=15)

In [75]:
model_KNN.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=15)

In [76]:
model_KNN.score(X_test,y_test)

1.0

In [77]:
model_KNN.score(X_test,y_test)

1.0

In [78]:
y_pred = model_KNN.predict(X_test)
y_pred

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa', 'setosa', 'setosa',
       'versicolor', 'setosa', 'setosa', 'virginica', 'versicolor',
       'setosa', 'setosa', 'setosa', 'virginica', 'versicolor',
       'versicolor', 'setosa', 'setosa', 'versicolor', 'virginica',
       'virginica', 'versicolor', 'virginica'], dtype=object)

In [79]:
from sklearn.svm import SVC

In [80]:
model_SVC = SVC(C=10, kernel='rbf', degree=3, gamma='scale')

In [81]:
model_SVC.fit(X_train,y_train)

SVC(C=10)

In [82]:
model_SVC.score(X_test,y_test)

0.98

# Now lets use the grid search CV

In [83]:
from sklearn.model_selection import GridSearchCV

In [84]:
classifier = GridSearchCV((model_SVC),{
        'kernel': ['poly'],
        'C': [0.1, 1, 10],
        'degree': [2, 3],
        'gamma': ['scale', 'auto']
    },cv=5, return_train_score=False)

In [85]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=10),
             param_grid={'C': [0.1, 1, 10], 'degree': [2, 3],
                         'gamma': ['scale', 'auto'], 'kernel': ['poly']})

In [86]:
res = pd.DataFrame(classifier.cv_results_)

In [87]:
res

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_degree,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003045,0.000728,0.002221,0.000634,0.1,2,scale,poly,"{'C': 0.1, 'degree': 2, 'gamma': 'scale', 'ker...",0.900000,0.966667,0.933333,0.900000,1.0,0.940000,0.038873,12
1,0.001773,0.000288,0.001595,0.000604,0.1,2,auto,poly,"{'C': 0.1, 'degree': 2, 'gamma': 'auto', 'kern...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
2,0.002264,0.000329,0.001487,0.000171,0.1,3,scale,poly,"{'C': 0.1, 'degree': 3, 'gamma': 'scale', 'ker...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
3,0.001916,0.000142,0.001375,0.000076,0.1,3,auto,poly,"{'C': 0.1, 'degree': 3, 'gamma': 'auto', 'kern...",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,7
4,0.001959,0.000107,0.001332,0.000074,1.0,2,scale,poly,"{'C': 1, 'degree': 2, 'gamma': 'scale', 'kerne...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
5,0.002982,0.000188,0.002455,0.000656,1.0,2,auto,poly,"{'C': 1, 'degree': 2, 'gamma': 'auto', 'kernel...",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,5
6,0.002012,0.000635,0.001375,0.000272,1.0,3,scale,poly,"{'C': 1, 'degree': 3, 'gamma': 'scale', 'kerne...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,4
7,0.002589,0.000950,0.001345,0.000179,1.0,3,auto,poly,"{'C': 1, 'degree': 3, 'gamma': 'auto', 'kernel...",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,7
8,0.001747,0.000102,0.001225,0.000048,10.0,2,scale,poly,"{'C': 10, 'degree': 2, 'gamma': 'scale', 'kern...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,6
9,0.001725,0.000159,0.001238,0.000073,10.0,2,auto,poly,"{'C': 10, 'degree': 2, 'gamma': 'auto', 'kerne...",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,7
10,0.002362,0.000593,0.001958,0.000888,10.0,3,scale,poly,"{'C': 10, 'degree': 3, 'gamma': 'scale', 'kern...",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,7
11,0.004156,0.002140,0.001415,0.000287,10.0,3,auto,poly,"{'C': 10, 'degree': 3, 'gamma': 'auto', 'kerne...",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,7

In [88]:
res[['param_C','param_kernel','mean_test_score']]

    param_C param_kernel  mean_test_score
0       0.1         poly         0.940000
1       0.1         poly         0.986667
2       0.1         poly         0.986667
3       0.1         poly         0.966667
4       1.0         poly         0.986667
5       1.0         poly         0.973333
6       1.0         poly         0.980000
7       1.0         poly         0.966667
8      10.0         poly         0.966667
9      10.0         poly         0.966667
10     10.0         poly         0.966667
11     10.0         poly         0.966667

In [89]:
classifier2 = GridSearchCV((model_KNN),{
        'n_neighbors': [3, 5, 7, 9, 11],
        'weights': ['uniform', 'distance'],
        'metric': ['euclidean', 'manhattan'],
    },
    cv=5,
    return_train_score=False
)

In [90]:
classifier2.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=15),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']})

In [91]:
res = pd.DataFrame(classifier2.cv_results_)

In [92]:
res

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001852,0.000252,0.002981,0.000493,euclidean,3,uniform,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,11
1,0.002530,0.000996,0.002240,0.000577,euclidean,3,distance,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,11
2,0.001562,0.000070,0.002176,0.000046,euclidean,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
3,0.001398,0.000066,0.001619,0.000056,euclidean,5,distance,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,11
4,0.001411,0.000069,0.002101,0.000104,euclidean,7,uniform,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,2
5,0.001478,0.000075,0.001690,0.000072,euclidean,7,distance,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,2
6,0.001450,0.000033,0.002177,0.000078,euclidean,9,uniform,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,6
7,0.001406,0.000036,0.001702,0.000033,euclidean,9,distance,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,6
8,0.001436,0.000079,0.002166,0.000076,euclidean,11,uniform,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.933333,1.000000,1.000000,0.966667,1.0,0.980000,0.026667,2
9,0.002790,0.000944,0.002808,0.000395,euclidean,11,distance,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
10,0.003182,0.000692,0.005514,0.002167,manhattan,3,uniform,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,19
11,0.003455,0.001193,0.003718,0.000945,manhattan,3,distance,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,19
12,0.006402,0.002455,0.007214,0.002812,manhattan,5,uniform,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,15
13,0.002855,0.000319,0.003536,0.000480,manhattan,5,distance,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,15
14,0.006084,0.000919,0.010064,0.004538,manhattan,7,uniform,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,6
15,0.004612,0.001882,0.009012,0.004652,manhattan,7,distance,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,15
16,0.002894,0.000640,0.003478,0.000204,manhattan,9,uniform,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,6
17,0.002562,0.000393,0.002787,0.000350,manhattan,9,distance,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,15
18,0.003685,0.001480,0.006594,0.002095,manhattan,11,uniform,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,2
19,0.002081,0.000197,0.002347,0.000185,manhattan,11,distance,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,11

In [93]:
res.sort_values(by='mean_test_score', ascending=False).head(10)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
9,0.002790,0.000944,0.002808,0.000395,euclidean,11,distance,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.966667,1.0,1.000000,0.966667,1.0,0.986667,0.016330,1
5,0.001478,0.000075,0.001690,0.000072,euclidean,7,distance,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
4,0.001411,0.000069,0.002101,0.000104,euclidean,7,uniform,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
8,0.001436,0.000079,0.002166,0.000076,euclidean,11,uniform,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.933333,1.0,1.000000,0.966667,1.0,0.980000,0.026667,2
18,0.003685,0.001480,0.006594,0.002095,manhattan,11,uniform,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
7,0.001406,0.000036,0.001702,0.000033,euclidean,9,distance,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,6
14,0.006084,0.000919,0.010064,0.004538,manhattan,7,uniform,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.966667,1.0,0.966667,0.933333,1.0,0.973333,0.024944,6
2,0.001562,0.000070,0.002176,0.000046,euclidean,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,6
16,0.002894,0.000640,0.003478,0.000204,manhattan,9,uniform,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.966667,1.0,0.966667,0.933333,1.0,0.973333,0.024944,6
6,0.001450,0.000033,0.002177,0.000078,euclidean,9,uniform,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.0,0.966667,0.933333,1.0,0.973333,0.024944,6

# Implement Random Search CV

In [95]:
from sklearn.model_selection import RandomizedSearchCV

In [96]:
classifier_r = RandomizedSearchCV((model_SVC),{
    'kernel': ['poly'],
        'C': [0.1, 1, 10],
        'degree': [2, 3],
        'gamma': ['scale', 'auto']
    },n_iter=4,cv=5, return_train_score=False)

In [97]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=10), n_iter=4,
                   param_distributions={'C': [0.1, 1, 10], 'degree': [2, 3],
                                        'gamma': ['scale', 'auto'],
                                        'kernel': ['poly']})

In [98]:
results = pd.DataFrame(classifier_r.cv_results_)

In [99]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_gamma,param_degree,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004029,0.001800,0.002333,0.000295,poly,scale,2,1.0,"{'kernel': 'poly', 'gamma': 'scale', 'degree':...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
1,0.003575,0.000095,0.002501,0.000090,poly,scale,2,0.1,"{'kernel': 'poly', 'gamma': 'scale', 'degree':...",0.900000,0.966667,0.933333,0.900000,1.0,0.940000,0.038873,4
2,0.004621,0.001612,0.002586,0.000211,poly,auto,3,1.0,"{'kernel': 'poly', 'gamma': 'auto', 'degree': ...",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,3
3,0.003932,0.001296,0.002849,0.000527,poly,scale,2,10.0,"{'kernel': 'poly', 'gamma': 'scale', 'degree':...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,2

In [101]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0      1.0         poly         0.986667
1      0.1         poly         0.940000
2      1.0         poly         0.966667
3     10.0         poly         0.966667